on: push
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Configure, build, and test the project
        run: |
          cd Native/
          cmake ./
          make
      - uses: actions/upload-artifact@v2
        with:
          path: Native\libmikktspace.so
          name: linux_x64_libmikktspace.so
      - run: |
          cd Native/
          ${{ env.ANDROID_NDK_HOME }}/ndk-build
      - uses: actions/upload-artifact@v2
        with:
          path: Native/libs/armeabi-v7a/libmikktspace.so
          name: android_ARMv7_libmikktspace.so