on: push
jobs:
  buildLinux:
    runs-on: ubuntu-latest
    env:
      VERSION: ${{ github.event.release.tag_name }}
    steps:
      - uses: actions/checkout@v3
      - uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c
        env:
          ANDROID_NDK_HOME: ${{ steps.setup-ndk.outputs.ndk-path }}
      - name: Build Native Linux
        run: |
          cd Native/
          cmake ./
          make
          ls -ao
      - uses: actions/upload-artifact@v3
        with:
          path: Native/libmikktspace.so
          name: linux_x64_libmikktspace.so
      - name: Build Native Arm/Android
        run: |
          cd Native/
          ndk-build
      - uses: actions/upload-artifact@v3
        with:
          path: Native/libs/armeabi-v7a/libmikktspace.so
          name: android_ARMv7_libmikktspace.so
  buildWindows:
    needs: [buildLinux]
    env:
      VERSION: ${{ github.event.release.tag_name }}
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - name: Build Native Windows
        run: |
          cd Native/
          cmake ./
          cmake --build ./ --config Release
          dir
      - name: Setup .NET 7
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: 7.0.x
      - name: Build Managed
        run: |
          cd CSharp
          dotnet restore
          dotnet build --configuration Release --no-restore
      - name: Download Native Libraries
        uses: actions/download-artifact@v3
        with:
          path: runtimes/
      - name: Display structure of downloaded files
        run: ls -R
        working-directory: runtimes/
      - name: Pack
        run: |
          cd CSharp
          dotnet pack --output nupkgs --configuration Release -p:Version=0.1.0